##################################
#                                #
#           SETTINGS             #
#                                #
##################################


settings:
  hearts:
    starter: 10
    unban: 5
    maximum: 30
