name: LSC3
version: '${project.version}'
main: com.sonmiike.lsc3.LSC3
api-version: 1.20
commands:
  life:
    aliases: [l, lifesteal, lifestealcore, lsc]
  bind:
  check:
    aliases: [status]
  beacons: